# Manipulating NumPy Arrays

## Table of contents
* [Create and print a one-dimensional (1-D) with 20 numerical items](#a)
* [Print the dimension of the array](#b) 
* [Print the array value for index equal 10](#c)
* [Slice and print the array between 5 and 15 indexes. Include both of the arrays](#d)
* [Print the data type of the array](#e)
* [Make a copy of the array and print it](#f)
* [Make a view of the array and print it](#g)
* [Print the shape of the array](#h)
* [Reshape the array and print it](#i)

In [47]:
def main():
  print("Manipulating NumPy Arrays")
if __name__ == "__main__":
  main()

Manipulating NumPy Arrays


<a id='a'></a>
#### Create and print a one-dimensional (1-D) with 20 numerical items

In [48]:
# importing NumPy library
import numpy as np
# Using arange() function to create a one dimension array 
one_d_array = np.arange(start=2,stop=41,step=2)
print("One-dimension array of 20 elements: {}".format(one_d_array))

One-dimension array of 20 elements: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


<a id='b'></a>
#### Print the dimension of the array

In [49]:
# ndim() function shows the number of dimension
print("The dimension of the array is: {}".format(np.ndim(one_d_array)))

The dimension of the array is: 1


<a id='c'></a>
Print the array value for index equal 10

In [50]:
print("Value in index 10 is: {}".format(one_d_array[10]))

Value in index 10 is: 22


<a id='d'></a>
Slice and print the array between 5 and 15 indexes. Include both of the arrays


In [51]:
# indexes 5 and 15 included in the array
sliced_array = one_d_array[5:16]
print("The original array before slicing is: {}".format(one_d_array))
print("Sliced array from 5 to 15 indexes are: {}".format(sliced_array))

The original array before slicing is: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
Sliced array from 5 to 15 indexes are: [12 14 16 18 20 22 24 26 28 30 32]


<a id='e'></a>
Print the data type of the array


In [52]:
# dtype() function shows the data type of the two arrays
print("The data type of the original array is: {}\nThe sliced array is: {}".format(one_d_array.dtype,sliced_array.dtype))

The data type of the original array is: int64
The sliced array is: int64


<a id='f'></a>
Make a copy of the array and print it


In [53]:
array_copy = one_d_array.copy()
print("This is a copy array of the original array: {}".format(array_copy))

This is a copy array of the original array: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


<a id='g'></a>
Make a view of the array and print it


In [54]:
array_view = one_d_array.view()
print("This is a view array of the original array: {}".format(array_view))

This is a view array of the original array: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


<a id='h'></a>
Print the shape of the array


In [55]:
# shape() function shows the shape of the array
print("The shape of the original array is: {}".format(one_d_array.shape))

The shape of the original array is: (20,)


<a id='i'></a>
Reshape the array and print it

In [56]:
# reshape() funcion used to make a 5x4 array 
print("Reshaping the array into 5 rows and 4 columns: \n{}".format(one_d_array.reshape(5,4)))

Reshaping the array into 5 rows and 4 columns: 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]]
